version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    hostname: ""
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_AR"
      LIST_DB: "true"
      ODOO_BUS_PUBLIC_SAMESITE_WS: 1
      PGHOST: do-cetmix-17-0-prod-db
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: ""
      traefik.enable: "true"
      traefik.domain: ""
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host(``);Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
      traefik.main-0.frontend.rule: Host(``)
      traefik.longpolling-0.frontend.rule: Host(``);Path:/websocket,/websocket/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.do-cetmix-17-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.do-cetmix-17-0-prod-compress.compress: "true"
      traefik.http.middlewares.do-cetmix-17-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag:
        "noindex, nofollow"
      traefik.http.middlewares.do-cetmix-17-0-prod-addSTS.headers.forceSTSHeader: "true"
      traefik.http.middlewares.do-cetmix-17-0-prod-forceSecure.redirectScheme.scheme: https
      traefik.http.middlewares.do-cetmix-17-0-prod-forceSecure.redirectScheme.permanent: "true"
      traefik.http.middlewares.do-cetmix-17-0-prod-override-ws-headers.headers.customRequestHeaders.X-Forwarded-Proto: "https"
      traefik.http.services.do-cetmix-17-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.do-cetmix-17-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.do-cetmix-17-0-prod-main-0.rule: Host()
      traefik.http.routers.do-cetmix-17-0-prod-main-0.service: do-cetmix-17-0-prod-main
      traefik.http.routers.do-cetmix-17-0-prod-main-0.middlewares:
        do-cetmix-17-0-prod-addSTS, do-cetmix-17-0-prod-buffering,
        do-cetmix-17-0-prod-compress, do-cetmix-17-0-prod-forceSecure
      traefik.http.routers.do-cetmix-17-0-prod-main-0.priority: 1
      traefik.http.routers.do-cetmix-17-0-prod-main-secure-0.rule: Host()
      traefik.http.routers.do-cetmix-17-0-prod-main-secure-0.service: do-cetmix-17-0-prod-main
      traefik.http.routers.do-cetmix-17-0-prod-main-secure-0.middlewares:
        do-cetmix-17-0-prod-addSTS, do-cetmix-17-0-prod-buffering,
        do-cetmix-17-0-prod-compress, do-cetmix-17-0-prod-forceSecure
      traefik.http.routers.do-cetmix-17-0-prod-main-secure-0.priority: 1
      traefik.http.routers.do-cetmix-17-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.do-cetmix-17-0-prod-main-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-0.rule:
        Host() && Path(`/websocket`)
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-0.service: do-cetmix-17-0-prod-longpolling
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-0.middlewares:
        do-cetmix-17-0-prod-addSTS, do-cetmix-17-0-prod-forceSecure,
        do-cetmix-17-0-prod-override-ws-headers
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-0.priority: 10
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-secure-0.rule:
        Host() && Path(`/websocket`)
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-secure-0.service: do-cetmix-17-0-prod-longpolling
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-secure-0.middlewares:
        do-cetmix-17-0-prod-addSTS, do-cetmix-17-0-prod-forceSecure,
        do-cetmix-17-0-prod-override-ws-headers
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-secure-0.priority: 10
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.do-cetmix-17-0-prod-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-0.rule:
        Host() && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`,
        `/website/info`))
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-0.service: do-cetmix-17-0-prod-main
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-0.middlewares:
        do-cetmix-17-0-prod-addSTS, do-cetmix-17-0-prod-buffering,
        do-cetmix-17-0-prod-compress, do-cetmix-17-0-prod-forbid-crawlers,
        do-cetmix-17-0-prod-forceSecure
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-0.priority: 10
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-secure-0.rule:
        Host() && (PathPrefix(`/web/`, `/website/info/`) || Path(`/web`,
        `/website/info`))
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-secure-0.service: do-cetmix-17-0-prod-main
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-secure-0.middlewares:
        do-cetmix-17-0-prod-addSTS, do-cetmix-17-0-prod-buffering,
        do-cetmix-17-0-prod-compress, do-cetmix-17-0-prod-forbid-crawlers,
        do-cetmix-17-0-prod-forceSecure
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-secure-0.priority: 10
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.do-cetmix-17-0-prod-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-0.rule:
        Host() && (PathPrefix(`/web/image/website/`) || Path(`/web/image/website`))
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-0.service: do-cetmix-17-0-prod-main
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-0.middlewares:
        do-cetmix-17-0-prod-addSTS, do-cetmix-17-0-prod-buffering,
        do-cetmix-17-0-prod-compress, do-cetmix-17-0-prod-forceSecure
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-0.priority: 100
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-secure-0.rule:
        Host() && (PathPrefix(`/web/image/website/`) || Path(`/web/image/website`))
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-secure-0.service: do-cetmix-17-0-prod-main
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-secure-0.middlewares:
        do-cetmix-17-0-prod-addSTS, do-cetmix-17-0-prod-buffering,
        do-cetmix-17-0-prod-compress, do-cetmix-17-0-prod-forceSecure
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-secure-0.priority: 100
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-secure-0.tls: "true"
      traefik.http.routers.do-cetmix-17-0-prod-allowedCrawlers-secure-0.tls.certResolver: letsencrypt

  db:
    extends:
      file: common.yaml
      service: db
    environment:
      DB_HOST: do-cetmix-17-0-prod-db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - "do-cetmix-17-0-prod-db"
    ports:
      - "5432:5432"

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
